CREATE OR REPLACE FUNCTION public.post_loan_payment_rpc(p_loan_id text, p_period integer, p_date date, p_interest_to_pay numeric)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
                                                                                                                                                                                                                                                                    DECLARE
                                                                                                                                                                                                                                                                        v_loan RECORD;
                                                                                                                                                                                                                                                                            v_entry JSONB;
                                                                                                                                                                                                                                                                                v_principal NUMERIC;
                                                                                                                                                                                                                                                                                    v_cash_acc TEXT;
                                                                                                                                                                                                                                                                                        v_loan_acc TEXT;
                                                                                                                                                                                                                                                                                            v_interest_acc TEXT;
                                                                                                                                                                                                                                                                                                v_journal_id TEXT;
                                                                                                                                                                                                                                                                                                    v_desc TEXT;
                                                                                                                                                                                                                                                                                                        v_is_received BOOLEAN;
                                                                                                                                                                                                                                                                                                            v_company_id TEXT;
                                                                                                                                                                                                                                                                                                                v_contact_id TEXT;
                                                                                                                                                                                                                                                                                                                    v_schedule JSONB;
                                                                                                                                                                                                                                                                                                                        v_new_schedule JSONB := '[]'::jsonb;
                                                                                                                                                                                                                                                                                                                            v_item JSONB;
                                                                                                                                                                                                                                                                                                                                v_is_interest_only BOOLEAN := FALSE;
                                                                                                                                                                                                                                                                                                                                    v_total NUMERIC;
                                                                                                                                                                                                                                                                                                                                    BEGIN
                                                                                                                                                                                                                                                                                                                                        SELECT * INTO v_loan FROM docs_loans WHERE id = p_loan_id FOR UPDATE;
                                                                                                                                                                                                                                                                                                                                            IF NOT FOUND THEN RAISE EXCEPTION 'Loan not found'; END IF;

                                                                                                                                                                                                                                                                                                                                                v_company_id := v_loan.company_id;
                                                                                                                                                                                                                                                                                                                                                    v_contact_id := (v_loan.data->>'contactId');
                                                                                                                                                                                                                                                                                                                                                        v_is_received := (v_loan.data->>'type') = 'RECEIVED';
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                -- Find schedule entry
                                                                                                                                                                                                                                                                                                                                                                    v_schedule := v_loan.data->'amortizationSchedule';
                                                                                                                                                                                                                                                                                                                                                                        v_principal := 0;
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                FOR v_item IN SELECT * FROM jsonb_array_elements(v_schedule) LOOP
                                                                                                                                                                                                                                                                                                                                                                                        IF (v_item->>'period')::INT = p_period THEN
                                                                                                                                                                                                                                                                                                                                                                                                    v_principal := (v_item->>'principal')::NUMERIC;
                                                                                                                                                                                                                                                                                                                                                                                                            END IF;
                                                                                                                                                                                                                                                                                                                                                                                                                END LOOP;
                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                        v_total := v_principal + p_interest_to_pay;
                                                                                                                                                                                                                                                                                                                                                                                                                            v_desc := 'Loan Payment Period ' || p_period::TEXT || ': ' || COALESCE(v_loan.data->>'name', v_loan.data->>'number');
                                                                                                                                                                                                                                                                                                                                                                                                                                v_journal_id := 'JE-LPAY-' || p_loan_id || '-' || p_period::TEXT;

                                                                                                                                                                                                                                                                                                                                                                                                                                    SELECT id INTO v_cash_acc FROM docs_accounts WHERE (code = '100100' OR sub_type IN ('CASH', 'BANK')) AND company_id = v_company_id LIMIT 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                        IF v_is_received THEN
                                                                                                                                                                                                                                                                                                                                                                                                                                                SELECT id INTO v_loan_acc FROM docs_accounts WHERE code = '210100' AND company_id = v_company_id LIMIT 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        SELECT id INTO v_interest_acc FROM docs_accounts WHERE code = '600000' AND company_id = v_company_id LIMIT 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                IF v_interest_acc IS NULL THEN SELECT id INTO v_interest_acc FROM docs_accounts WHERE type = 'EXPENSE' AND name ILIKE '%interest%' AND company_id = v_company_id LIMIT 1; END IF;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ELSE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            SELECT id INTO v_loan_acc FROM docs_accounts WHERE code = '100601' AND company_id = v_company_id LIMIT 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    SELECT id INTO v_interest_acc FROM docs_accounts WHERE code = '400500' AND company_id = v_company_id LIMIT 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            IF v_interest_acc IS NULL THEN SELECT id INTO v_interest_acc FROM docs_accounts WHERE type = 'REVENUE' AND name ILIKE '%interest%' AND company_id = v_company_id LIMIT 1; END IF;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                END IF;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    -- Update Loan Document
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        UPDATE docs_loans SET 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                paid_periods = array_append(COALESCE(paid_periods, ARRAY[]::INT[]), p_period),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        status = CASE WHEN array_length(array_append(COALESCE(paid_periods, ARRAY[]::INT[]), p_period), 1) = (v_loan.data->>'termMonths')::INT THEN 'PAID' ELSE status END,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                updated_at = NOW()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    WHERE id = p_loan_id;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        -- Insert Journal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            INSERT INTO docs_journals (id, company_id, date, journal_date, journal_type, status, reference_number, data, updated_at)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                VALUES (v_journal_id, v_company_id, p_date, p_date, 'LOAN_PAYMENT', 'POSTED', v_loan.data->>'number' || '/P' || p_period::TEXT, '{}'::jsonb, NOW())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ON CONFLICT (id) DO UPDATE SET status = 'POSTED', updated_at = NOW();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        DELETE FROM docs_journal_lines WHERE journal_id = v_journal_id;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                IF v_is_received THEN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        INSERT INTO docs_journal_lines (id, journal_id, company_id, account_id, debit, credit, description) VALUES (v_journal_id || '-dr1', v_journal_id, v_company_id, v_loan_acc, v_principal, 0, v_desc);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                IF p_interest_to_pay > 0 THEN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            INSERT INTO docs_journal_lines (id, journal_id, company_id, account_id, debit, credit, description) VALUES (v_journal_id || '-dr2', v_journal_id, v_company_id, v_interest_acc, p_interest_to_pay, 0, v_desc);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    END IF;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            INSERT INTO docs_journal_lines (id, journal_id, company_id, account_id, debit, credit, description) VALUES (v_journal_id || '-cr', v_journal_id, v_company_id, v_cash_acc, 0, v_total, v_desc);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ELSE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        INSERT INTO docs_journal_lines (id, journal_id, company_id, account_id, debit, credit, description) VALUES (v_journal_id || '-dr', v_journal_id, v_company_id, v_cash_acc, v_total, 0, v_desc);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                INSERT INTO docs_journal_lines (id, journal_id, company_id, account_id, debit, credit, description) VALUES (v_journal_id || '-cr1', v_journal_id, v_company_id, v_loan_acc, 0, v_principal, v_desc);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        IF p_interest_to_pay > 0 THEN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    INSERT INTO docs_journal_lines (id, journal_id, company_id, account_id, debit, credit, description) VALUES (v_journal_id || '-cr2', v_journal_id, v_company_id, v_interest_acc, 0, p_interest_to_pay, v_desc);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            END IF;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                END IF;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    RETURN jsonb_build_object('success', true, 'journal_id', v_journal_id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    END;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $function$
